### ISSUE TITLE
Message on activity log?

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#7]
I think that should be good if you write a message on the activity log menu on the dashboard that says: "No applications running" or something like that when there are no applications running. 

@netbeast/engineering

**Comment by jsdario** [comment]
<img width="941" alt="screen shot 2015-12-14 at 14 29 55" src="https://cloud.githubusercontent.com/assets/5166506/11782104/2eac9622-a26f-11e5-86fb-22d42c17f934.png">

Added some! 

By the moment is only shown if there are no activities on "refresh" but this has to improve. The fact is that this visualisation code is written on the _view_ rather than the activity _directive_ and does not update properly the number of activities running.

I will leave this issue open until it is completely fixed.
